-- +goose Up
CREATE TABLE groups (
	id VARCHAR(20) PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	description TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE groups;